### ISSUE TITLE
BUILD_UVW_LIBS doesn't work on Windows (no symbols are exported)

### ISSUE THREAD

**Issue by amurzeau** [skypjack/uvw#196]
Hi,

When building UVW as a shared library (by setting BUILD_UVW_LIBS to ON) on Windows, a DLL is created but without any .lib file.
The issue is that nothing is exported using__declspec(dllexport).

I suggest to make the same thing as libuv, that is:
https://github.com/libuv/libuv/blob/36549815eed297c74448ff580b5c84713245ec5d/include/uv.h#L30

And putting the equivalent of UV_EXTERN to classes and functions.
This would allow to use -fvisibility=hidden with gcc too.

Are you willing to support that ?

Thanks :)

**Comment by stefanofiorentino** [comment]
@amurzeau have you a working sample? 
I'll dive into this asap.

**Comment by skypjack** [comment]
@amurzeau good point, the CI tests the flag with VS2019 but it doesn't really link to any library.

>Are you willing to support that ?

Sure, this makes perfectly sense. Did you have a try with it and have something to attach to a PR eventually?
This would speed up the whole thing a little. I'm short in time at the moment and it will take a while otherwise.

**Comment by amurzeau** [comment]
Yes I've tried it and tested it by linking tests to uvw-shared instead of uvw-static.
I can come with a PR for an overview of the solution

**Comment by skypjack** [comment]
That would be great. If you had code to use as a starting point, you could speed up the whole process a lot. Thanks!

**Comment by amurzeau** [comment]
I see that in CMakeLists.txt in tests there is:
```cmake
$<$<TARGET_EXISTS:uvw::uvw>:uv::uv-static>
$<$<TARGET_EXISTS:uvw::uvw-static>:uvw::uvw-static>
```

Should'nt that be this instead ?:
```cmake
target_link_libraries(
         ${TEST_NAME}
         PRIVATE
             $<$<TARGET_EXISTS:uvw::uvw>:uvw::uvw>
-            $<$<TARGET_EXISTS:uvw::uvw>:uv::uv-static>
-            $<$<TARGET_EXISTS:uvw::uvw-static>:uvw::uvw-static>
+            $<$<TARGET_EXISTS:uv::uv-shared>:uv::uv-shared>
+            $<$<TARGET_EXISTS:uvw::uvw-shared>:uvw::uvw-shared>
             GTest::Main
             Threads::Threads
             ${LIBRT}
             ${WINSOCK2}
         )
```

**Comment by amurzeau** [comment]
In the process when executing tests, I've found that there is a nasty thing.
The Emitter class contains static variables which are splitted when using a shared library.
The static variable in the shared library is not at the same address as the one in the user executable (like `main` test).
They are `next_type` and `event_type`. They return different things based on whether the call came from the user code (when doing `tcp->on<Event>` for example) and libuvw code (when a callback is called from libuv).

These static variables need to be put in a cpp file to make them unique between the shared library and the user executable. But that's not easy as they are in the Emitter template class, and event_type is a function template with the event type as template argument.
So this means there are many event_type and next_type instantiations, that's alot to explicitly instantiate (maybe between 20 and 30), but I don't have any other idea than to explicitly instantiate them.

Actually, because of this, I think uvw can't be used as a shared library.

I've encountered the issue after executing ctest on linux with a build compiled by clang 9.
The uvw_main test will just hang (or assert in the error handler) because of event_type index mismatchs between user executable and libuvw-shared.so.

Do you have a better idea to fix this than explicitly instantiate event_type() and next_type() for all required cases ?

**Comment by amurzeau** [comment]
Well, the shared library case should works fine when everything is exported. So there must be a way to do the same explicitely.

**Comment by stefanofiorentino** [comment]
@amurzeau I confess I work all the time with static linking, so thank you to have throughly tested the shared one. Now I'm a bit lost on what's your proposal because I need to mix-and-match issue and proposals. 

- the original question is solved by your PR, isn't it?

- explicitly instantiate the `event_type`-related statics in `.cpp` files solves the issue of different instantiation user_code and library one, we can do that without any further doubts.

- for the target-link-libraries I think the version on the master is correct as we want to link uv_a (static) also in case we define uvw::uvw

Do you agree with the summary?

**Comment by amurzeau** [comment]
Yes I agree, some comment for each of them:

> the original question is solved by your PR, isn't it?

Yes, but that require fixing the second issue about event_type/next_type statics so there is one instance between the shared object and the executable


> explicitly instantiate the event_type-related statics in .cpp files solves the issue of different instantiation user_code and library one, we can do that without any further doubts.

This is an issue that arise when symbols are hidden by default. It needs to be fixed to support DLL on Windows, and default hidden symbols on linux.

> for the target-link-libraries I think the version on the master is correct as we want to link uv_a (static) also in case we define uvw::uvw

Yes, this is a separate thing which is not required to support DLLs.

**Comment by amurzeau** [comment]
The PR is supposed to fix the first 2 issues, but I can remove any related to the 3rd one.
I have to go, but I think I have a solution about next_type/event_type without explicit instantiations: put UVW_EXTERN on the Emitter class template.
This mostly works, but I get test failure still, something is still missing:
```
The following tests FAILED:
          5 - uvw_file_req (Failed)
          8 - uvw_fs_req (Failed)
```

**Comment by skypjack** [comment]
I've faced a similar problem with `EnTT` (another project of mine) and I solved it somehow.
Unfortunately, because of an idiosincracy of msvc, you've to split that part to make it work in all cases but it's _solvable_ anyway.

If we accept to make it work only for linked libraries, it's also way easier to solve. That is, plugins loaded at runtime on which the linker has no clue won't work properly without an extra layer of complexity but I think it's acceptable for this kind of libraries.
Moreover, we can make it fully configurable and sfinae-friendly, so that in the worst case one can make it work anyway by listing explicitly all types when it comes to working with pure plugins.

**Comment by stefanofiorentino** [comment]
> put UVW_EXTERN on the Emitter class template.

Being Emitter<T> a template for a limited number of typenames T, I would prefer to explicitly instantiate functions for all available types. @amurzeau Your proposal looks more elegant, though. I guess it's just a matter of taste.

> If we accept to make it work only for linked libraries, it's also way easier to solve. 

I have worked on a couple of plugin system in the past with plugin's init() accepting pointer to the singleton in the user_space. @skypjack I agree this extra layer is application dependant, so not generalizable at current level.

**Comment by amurzeau** [comment]
The issue with explicit instantiations is that it is something more to maintain.

An alternative solution is to extract the identifier generation (next_type and event_type) that uses static variables into a non-templated thing that would be in a cpp file.

**Comment by stefanofiorentino** [comment]
@amurzeau, please, let me know once you update your PR (also if FS-related tests are failing).

**Comment by amurzeau** [comment]
Using gdb, I was able to find which instantiation are required if we go this route, there are more than 100:

```cpp
uvw::Emitter<uvw::FileReq>::next_type()::counter
uvw::Emitter<uvw::AsyncHandle>::next_type()::counter
uvw::Emitter<uvw::CheckHandle>::next_type()::counter
uvw::Emitter<uvw::GetAddrInfoReq>::next_type()::counter
uvw::Emitter<uvw::GetNameInfoReq>::next_type()::counter
uvw::Emitter<uvw::FileReq>::next_type()::counter
uvw::Emitter<uvw::FsReq>::next_type()::counter
uvw::Emitter<uvw::FsEventHandle>::next_type()::counter
uvw::Emitter<uvw::FsPollHandle>::next_type()::counter
uvw::Emitter<uvw::IdleHandle>::next_type()::counter
uvw::Emitter<uvw::Loop>::next_type()::counter
uvw::Emitter<uvw::PipeHandle>::next_type()::counter
uvw::Emitter<uvw::details::ConnectReq>::next_type()::counter
uvw::Emitter<uvw::PollHandle>::next_type()::counter
uvw::Emitter<uvw::PrepareHandle>::next_type()::counter
uvw::Emitter<uvw::ProcessHandle>::next_type()::counter
uvw::Emitter<uvw::SignalHandle>::next_type()::counter
uvw::Emitter<uvw::details::ShutdownReq>::next_type()::counter
uvw::Emitter<uvw::TCPHandle>::next_type()::counter
uvw::Emitter<uvw::TimerHandle>::next_type()::counter
uvw::Emitter<uvw::TTYHandle>::next_type()::counter
uvw::Emitter<uvw::details::SendReq>::next_type()::counter
uvw::Emitter<uvw::UDPHandle>::next_type()::counter
uvw::Emitter<uvw::WorkReq>::next_type()::counter
```

```cpp
uvw::Emitter<uvw::FileReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)2> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)1> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)3> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)4> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)8> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)15> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)16> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)9> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)5> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)14> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)11> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)27> >()::value
uvw::Emitter<uvw::AsyncHandle>::event_type<uvw::AsyncEvent>()::value
uvw::Emitter<uvw::AsyncHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::CheckHandle>::event_type<uvw::CheckEvent>()::value
uvw::Emitter<uvw::CheckHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::GetAddrInfoReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::GetAddrInfoReq>::event_type<uvw::AddrInfoEvent>()::value
uvw::Emitter<uvw::GetNameInfoReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::GetNameInfoReq>::event_type<uvw::NameInfoEvent>()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)1> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)2> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)3> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)4> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)8> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)15> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)16> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)9> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)5> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)14> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)11> >()::value
uvw::Emitter<uvw::FileReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)27> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)25> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)32> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)17> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)19> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)20> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)35> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)36> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)18> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)22> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)6> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)7> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)34> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)21> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)29> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)12> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)13> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)10> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)23> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)24> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)28> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)26> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)30> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)31> >()::value
uvw::Emitter<uvw::FsReq>::event_type<uvw::FsEvent<(uvw::details::UVFsType)33> >()::value
uvw::Emitter<uvw::FsEventHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::FsEventHandle>::event_type<uvw::FsEventEvent>()::value
uvw::Emitter<uvw::FsPollHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::FsPollHandle>::event_type<uvw::FsPollEvent>()::value
uvw::Emitter<uvw::IdleHandle>::event_type<uvw::IdleEvent>()::value
uvw::Emitter<uvw::IdleHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::Loop>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::PipeHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::details::ConnectReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::details::ConnectReq>::event_type<uvw::ConnectEvent>()::value
uvw::Emitter<uvw::PipeHandle>::event_type<uvw::ConnectEvent>()::value
uvw::Emitter<uvw::PipeHandle>::event_type<uvw::CloseEvent>()::value
uvw::Emitter<uvw::PollHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::PollHandle>::event_type<uvw::PollEvent>()::value
uvw::Emitter<uvw::PollHandle>::event_type<uvw::CloseEvent>()::value
uvw::Emitter<uvw::PrepareHandle>::event_type<uvw::PrepareEvent>()::value
uvw::Emitter<uvw::PrepareHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::ProcessHandle>::event_type<uvw::ExitEvent>()::value
uvw::Emitter<uvw::ProcessHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::ProcessHandle>::event_type<uvw::CloseEvent>()::value
uvw::Emitter<uvw::SignalHandle>::event_type<uvw::SignalEvent>()::value
uvw::Emitter<uvw::SignalHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::details::ShutdownReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::details::ShutdownReq>::event_type<uvw::ShutdownEvent>()::value
uvw::Emitter<uvw::TCPHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::TCPHandle>::event_type<uvw::ConnectEvent>()::value
uvw::Emitter<uvw::TCPHandle>::event_type<uvw::CloseEvent>()::value
uvw::Emitter<uvw::TimerHandle>::event_type<uvw::TimerEvent>()::value
uvw::Emitter<uvw::TimerHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::TTYHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::TTYHandle>::event_type<uvw::CloseEvent>()::value
uvw::Emitter<uvw::details::SendReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::details::SendReq>::event_type<uvw::SendEvent>()::value
uvw::Emitter<uvw::UDPHandle>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::UDPHandle>::event_type<uvw::SendEvent>()::value
uvw::Emitter<uvw::UDPHandle>::event_type<uvw::UDPDataEvent>()::value
uvw::Emitter<uvw::UDPHandle>::event_type<uvw::CloseEvent>()::value
uvw::Emitter<uvw::WorkReq>::event_type<uvw::ErrorEvent>()::value
uvw::Emitter<uvw::WorkReq>::event_type<uvw::WorkEvent>()::value
```

**Comment by stefanofiorentino** [comment]
@skypjack could stop me anytime, but I guess is not easy to instantiate the FsEvent related to enum class UVFsType. Just guessing.

**Comment by amurzeau** [comment]
The issue is that the user executable also see the definition, and prefer to have its own definition rather than the one in the shared library.

Spliting the definition of next_type and event_type inside a different header that would be included only when building the shared library would fix this I think.

Then the user code will only see the declaration without any definition.

Then with UVW_EXTERN, all implicit intantiations should be exported from the shared lib. I will try that.

**Comment by stefanofiorentino** [comment]
> The issue with explicit instantiations is that it is something more to maintain.

I gave a [linux-only valid](https://github.com/stefanofiorentino/uvw/commit/70a80e99637c2b070e6a0d9d17fd3f9c8d51cb24) try to remove the static counter leveraging __PRETTY_FUNCTION__ .
Due to change from vector to unordered_map, we loose in performance, though.

**Comment by stefanofiorentino** [comment]
> Then the user code will only see the declaration without any definition.

A factory for event_type, sort of. Could work.

**Comment by amurzeau** [comment]
I don't like much loosing performance for this. My though is that is if this functionality is to be supported, it should not lower the performance of the current state of uvw.

I've tried what I've though here before: hidding definition from user code, and let the implicit instantiation be exported using UVW_EXTERN.
But this doesn't work well because not all functions in Emitter are used by the uvw library itself (only publish mostly).
And inlining can prevent a function to be exported.
So this is too random.

But I though of a different way to tackle this: avoid the statics and have a different way to get an unique index.
I'm trying to implement passing possible events as template arguments to Emitter. Then the index key for an event E would be its index in the parameter pack of possible events.
This should be fast enough, but less memory optimized: if the only used event is not the first one of the list of possible events, the handlers array will have hole of null unique_ptrs.

But this has the added benefit of preventing the user to try to listen for ListenEvent on a FsReq handle for example.

**Comment by skypjack** [comment]
@amurzeau I'm missing the reasons for which we can't simply export the index generator as we did for all the other things.
It's technically possible, so there must be a good reason for which we aren't pursuing this solution.

**Comment by amurzeau** [comment]
One solution would be to explicitly instantiate all variants of event_type. But there are many of them.

I've tried to export implicit instantiations, but I couldn't to reliably make this work (unless preventing inlining).

Explicit instantiation are too much of a maintenance burden to me, unless you are ok with hundreds of explicit instantiations.

Other solutions involving a unordered_map can reduce performance somewhat heavily (every callbacks would need a hash table lookup which is slower than just indexing an array).

This is why I'm looking for a different solution. Even if the code has only 2 static variables, after all possible implicit instantiations, there are in fact hundreds of static variables, so that's not as easy as expected to export them all.

**Comment by skypjack** [comment]
No, I mean, is there anything wrong with using the `declspec` tag also on the index generator?
I've been busy today and I didn't have a try with that but it seems a viable solution, so either I missed the comment where someone mentioned the reasons for which we cannot use it or I'm missing the point for which we aren't considering it.

**Comment by amurzeau** [comment]
declspec(dllimport) and having a definition isn't allowed.

#ifdefing the definition of event_type doesn't work because not all functions in Emitter are instantiated in the library itself, but are sometimes required by the user code.
I get linking errors when building tests against the DLL.

And it doesn't prevent the issue on linux that there are duplicate static variables (counter and value in next_type and event_type).
The user code and the shared library won't use the same static variable instance which cause mismatch when retrieving the handler.

**Comment by skypjack** [comment]
Got it. Thanks for clarifying. :+1:

**Comment by stefanofiorentino** [comment]
I think that the easy working solution could be to "round-robin" all possible instantiations (they are a lot but limited, so it is a viable solution). The instantiation I have to double check are instead the ones depending on the enum class uvw::details::UVFsType. This afternoon I stuck finding a way to instantiate this, without changing a lot of include chains.

**Comment by amurzeau** [comment]
I've something that works it seems, by adding event types as variadic parameters to Emitter.
The index is the position of the Event type in the parameter pack.

This has the benefit to check that only valid event are listened on a given handle/emitter.

And I found that the `test/signal.cpp` was listening for `CheckEvent` on a `SignalHandle`, is this valid ?
I don't think a `CheckEvent `can be triggered from a `SignalHandle`, but only from a `CheckHandle`.

**Comment by amurzeau** [comment]
Here is the implementation of removing the static variables and encoding the possible events in the Emitter type as a variadic template argument: https://github.com/skypjack/uvw/pull/197/commits/7f1149483229583a327607bfc1a3e37d8a95e45d

Instead of a std::vector, I've replaced it with a std::array as the maximum number of possible events is known now.

Because of a change in `tests/CMakeLists.txt` I've done in that PR, the tests are running with the shared library instead of the static one to check that it works fine.

**Comment by stefanofiorentino** [comment]
@amurzeau just to let you know I'm not shrugging off this. 
I could repeat this with visibility=hidden and I'm using your patch as starting point.
Just taking time to check if there is a more suitable solutions.

**Comment by amurzeau** [comment]
No worries, the commit I have made is somewhat big ^^

**Comment by stefanofiorentino** [comment]
Ciao @amurzeau, I have elaborated a [working solution](https://gist.github.com/stefanofiorentino/f49e459210b462b797ca884c05040887) on top of yours. 
It works only for BUILD_UVW_LIBS=ON and it's still broken for header-only version (default to BUILD_UVW_LIBS=OFF)
Could you please try this commit against your setup?
If successful, we `only' need to fix header-only version, reword, split and squash our commits.
Let me know if is it possible to you to reproduce correctly build and run tests with shared libs.

**Comment by amurzeau** [comment]
I've read your patch:
- You committed a patch file inside the commit 5ca341fa871a7e818a75275294b82d2b3555ca79.patch, this is probably an error
- To fix the build with headers only, maybe you can move `extern template` declarations in uvw.h into a separate header, and include that new one from uvw.h only when `BUILD_UVW_LIBS=ON` (same for the `type_factory.cpp` file)
- In emitter.h, you added `FakeEvent` and `TestEmitter`, this should be kept inside the tests I think. This tests ensure the user can create its own events I guess.
- Same for handle.hpp and `fake_handle_t` and `FakeHandle`.
- test/main.cpp is commented out

I think idea is good, but if the maintenance burder is too high and breaks things too much, I wouldn't mind if this issue is closed as too much work for what it gives.

Otherwise this seems ok to me :)

**Comment by stefanofiorentino** [comment]
@amurzeau could you please have a look at my [experimental](https://github.com/stefanofiorentino/uvw/commits/experimental)?

**Comment by stefanofiorentino** [comment]
@amurzeau did you eventually have a chance to try my proposal?
The only remaining flaw is the `FakeEvent`/`FakeHandle` symbols in the wrong place.

**Comment by amurzeau** [comment]
I've reviewed the changes on the commit itself on github (https://github.com/stefanofiorentino/uvw/commit/ba7a053eee5d9bda27b6d25d18bee03e748601ff)
Maybe you should make a PR to ease the review process

**Comment by stefanofiorentino** [comment]
@amurzeau if no more suitable solution is found, I'll close this in a couple of days.

**Comment by skypjack** [comment]
So, @stefanofiorentino and I have discussed _live_ another approach that should work and is probably easier to maintain in the long term than all the ones proposed so far.
The basic idea is to have handles and requests _announce_ the events they want to emit (as an exposed type or as a parameter pack for the base class - I've some doubts on the first one since the class isn't defined already when we need to use the exposed type), then make the `Emitter` class use an `std::tuple` for the handlers. This will allow to get them directly (as in `std::get`) without a performance loss.
The only drawback is that there will be potentially more implicit specializations of the `Emitter` class template (in the worst case, as many as are the different types for handles and requests, probably less though).

Of course, the other half of the solutions is what @amurzeau already proposed with his PR, that is the typical `declspec` hell we all know already. :smile:

**Comment by skypjack** [comment]
Side note: in the meantime, I'm merging on `master` the commit from @stefanofiorentino to make explicit that shared libraries aren't supported.
We'll rollback that one when we are done with the changes required to make them work seamlessly.

Any feedback is appreciated.

**Comment by stefanofiorentino** [comment]
Just to keep all you posted on this, I have a (quick and very dirty) [working solution](https://github.com/stefanofiorentino/uvw/tree/experimental-shared-lib) with the big CONs about much more explicit template instantiations than the static lib solution AND the /bigobj definition needed under WIN32. Though the compiled libs are comparatively lightweight, at build time the objects become very heavy.

**Comment by skypjack** [comment]
I like a lot the idea of having an extended emitter. Though, the instantiations looks a pain to maintain. 🤔

**Comment by skypjack** [comment]
Another approach could be that of giving a fixed, compile-time identifier to events.
There is a small number of them and it's unlikely it will grow in future. Moreover, they are known in advance. So, it seems viable with a small rework of the codebase.
What do you think about it?

**Comment by stefanofiorentino** [comment]
As per my understanding your last solution will keep the (monostate) event registry pattern as is, doesn't it?
As static instances and shared objects don't like each others too much, my intention was to completely remove the singleton/monostate from the project. 
I completely agree that with all these instantiations in place, we will shoot at ourselves foot.
I won't have effort to spend on this for a while, though.

**Comment by skypjack** [comment]
It won't. My idea is to get rid completely of static stuff, so that it won't interfere anymore with shared libs.
I want to assign compile-time identifiers to the even types. In fact, they aren't user defined. They are all known in advance and part of the library, so it seems feasible.
It only requires to move all event types to a single file probably. So, a little rework, but still...

**Comment by stefanofiorentino** [comment]
The entire solution is still not crystal clear to me, anyway having a fixed number of events, the compile-time identifiers is an elegant solution. 
Maybe we can have a brief chat on this next time we have concurrent free slots.

**Comment by skypjack** [comment]
> Maybe we can have a brief chat on this next time we have concurrent free slots.

Sure thing. I'm available more or less anytime at the moment. Ping me and cast your suggestion. 😉

**Comment by skypjack** [comment]
@stefanofiorentino let's try to set up a call: tomorrow morning or Monday any time?

**Comment by stefanofiorentino** [comment]
Based on our discussion I've committed a couple of PoC (AsyncHandle only).

The funcsig-based is very promising and requires little effort (at first look).
The enum-based requires further investigation about the size of the handlers vector (maybe for some Handle the vector will be much bigger than required. Switch to unordered_map is possible, though).

After 2 months, we had the chance to review it together and maybe we'll get a decision shortly.

**Comment by skypjack** [comment]
The funcisg/pretty function prototype has the same problem, doesn't it?
We have a hash in a 32b space, so we can't really use a vector in the emitter and some sort of mapping is required (either a standard map or a open hash probably).

**Comment by stefanofiorentino** [comment]
yup, the committed poc uses unordered_map

Il ven 2 apr 2021, 09:33 Michele Caini ***@***.***> ha
scritto:

**Comment by stefanofiorentino** [comment]
[here](https://github.com/stefanofiorentino/uvw/tree/remove-monostate) is a preparatory solution to this issue. 
recap:

- the event_type is built from a non-static template function (monostate removed)
- pretty_function/funcsig acts as the key of the unordered_map of handlers
- utility functions (i.e. empty) have been changed accordingly
